### PR TITLE
Implement Thunks and API call for GET /members

### PR DESCRIPTION
**Pull request by steven-steven**
1. Implement Redux-thunk
2. Implement api logic (using axios. Consist of `baseApi.js`, and `memberService.js`)
2. Implement normalizr (to restructure the data from the API before putting it into the redux store)
   - Define the schema to create seperate entities (ie. skills, interest, subteam) from the GET /members response
3. rename `store.js` to `rootReducer.js` and move the code for creating the store up to _app.js
4. rename `membersSlice.js` to `memberSlice.js`
5. In index.js, created an example that calls thunks `loadAllMembers()`. This is in getInitialProps() so the members data will be populated on load.

memberState

### CODE REVIEW

**Comment by steven-steven** [comment]
> This looks awesome, I was testing on a different port so I got 404 errors (I changed the hardcoded ports to import from a config file). But, we should probably handle any possible errors that might not return what we expect so that it doesn't crash the program (we should also think about standardized error messages from server to client soon as well).

Yikes. So when I put the wrong port, my page crashes with null exception because I didn't put any initial state in the store. I'll fix that so the app wont crash anymore.
But for api errors, currently there is only a catch block in the thunk that console log if axios returns some error. So we can replace that to trigger and display some toast message instead.

**Comment by kevinbai0** [comment]
Sorry for getting to this so late

Should we create a separate user reducer? One that contains the information of the user that is currently logged in. Then we can separate that from a list of all the members, which could also be separated from the current member selected (perhaps from the member list).

**Comment by steven-steven** [comment]
@kevinbai0 Sure. I can make a separate reducer for all the current user's settings. 
Sorry I don't fully understand what you mean by 'separating the current user from the list of all members' or 'separating it from the current member selected'. Can you clarify?

I'm just thinking.. We can have the current user information in the 'members' reducer, and then just storing the user_id in the 'user' reducer. Since the members are all stored as a dictionary, its easy to find, read and update based on that user_id. 
Another way is to store the current user's information in the 'user' reducer and not include it in the 'members' reducer. Because I don't think we should duplicate the current user's state in two places right. Which of these options were you thinking of?

**Comment by kevinbai0** [comment]
Like when a member is selected from the member list, that member should be stored in the redux store as the "current member selected", and we'd need to create a new API request to fetch the full contents of the user to pull up the member page. The "current user" refers to the member that is currently logged in (the user's own account).

**Comment by steven-steven** [comment]
I see. So we'll have something like: 
- 'member' reducer
   - current selected member and their full content
   - list of all members
- 'user' reducer
   - current authenticated user's account

**Comment by steven-steven** [comment]
1. I added the 'selectedMember' state where it's filled from GET /members/:id/info endpoint.
2. Created 'userSlice' reducer for authenticated user. I didn't implement any states yet. I believe authentication endpoint is not yet implemented right? So I'm not sure what sort of data will we have.

**Pull request merged**
